### ISSUE TITLE
Diseño de prototipo de realidad aumentada

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-equipo-edith#2]
[Practica 2 Diseño de prototipo.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-equipo-edith/files/8119985/Practica.2.Diseno.de.prototipo.pdf)

**Comment by JeserLeonel** [comment]
Excelente trabajo cumple con todos los criterios mencionados en la rubrica **20%**
💯 🥇

**Comment by josealfredo79** [comment]
Bien hecho y revisado
